<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2iTxnRc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2iTxnRc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2iTxnRc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2iTxnRc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2iTxnRc\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2iTxnRc',
    'container.build_id' => 'aee761a4',
    'container.build_time' => 1637838336,
));
